resource_types:
  - name: mediawiki-version-resource
    type: docker-image
    source:
      repository: droidwiki/mediawiki-version-resource
      tag: latest
  - name: ssh
    type: docker-image
    source:
      repository: droidwiki/concourse-ssh-resource
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: mediawiki-version
    type: mediawiki-version-resource
    source:
      mediawikiUrl: https://de.wikipedia.org
  - name: staging-server
    type: ssh
    source:
      host: 188.68.49.74
      user: ((ssh.username))
      private_key: ((ssh.private_key))
      timeout: 1800
  - name: slack-feed
    type: slack-notification
    source:
      url: ((slack.webhook_url))
  - name: mediawiki-config
    type: git
    source:
      uri: https://github.com/droidwiki/operations-mediawiki-config.git

jobs:
  - name: update-mediawiki
    plan:
      - get: mediawiki-version
        trigger: true
      - put: update mediawiki
        resource: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e
            set -x
            cd /data/deployment/staging/main/
            branch="|mediawiki-version|"

            rm -rf extensions
            rm -rf skins
            git fetch
            git checkout $branch
          placeholders:
            - name: "|mediawiki-version|"
              file: mediawiki-version/git-branch
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Updating of mediawiki failed. :sob:"
      - put: update extensions
        resource: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e
            set -x
            cd /data/deployment/staging/extensions/
            branch="|mediawiki-version|"
            newVersion=${branch:4}

            ../../bin/update-list.sh ../../bin/extensions.list $newVersion
          placeholders:
            - name: "|mediawiki-version|"
              file: mediawiki-version/git-branch
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Updating of extensions failed. :sob:"
      - put: update skins
        resource: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e
            set -x
            cd /data/deployment/staging/skins/
            branch="|mediawiki-version|"
            newVersion=${branch:4}

            ../../bin/update-list.sh ../../bin/skins.list $newVersion
          placeholders:
            - name: "|mediawiki-version|"
              file: mediawiki-version/git-branch
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Updating of skins failed. :sob:"

  - name: update-composer
    plan:
      - get: mediawiki-version
        passed: [update-mediawiki]
        trigger: true
      - put: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e
            set -x
            cd /data/deployment/staging
            ./create-links.sh

            cd main
            composer update --no-dev
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Updating of composer failed. :sob:"

  - name: update-mediawiki-config
    plan:
      - get: mediawiki-config
        trigger: true
      - put: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e
            ref="|mediawiki-config-ref|"

            echo "((ssh.private_key))" > /tmp/ssh-key
            chmod 600 /tmp/ssh-key
            eval `ssh-agent -s`
            ssh-add /tmp/ssh-key

            cd /data/deployment/staging/mw-config/mw-config

            git fetch && git checkout $ref

            composer update --ansi --no-progress --prefer-dist --profile -v
          placeholders:
            - name: "|mediawiki-config-ref|"
              file: mediawiki-config/.git/ref
        ensure:
          put: staging-server
          params:
            interpreter: /bin/bash
            script: |
              export TERM=dumb
              set -e

              rm -rf /tmp/ssh-key
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Updating of composer failed. :sob:"

  - name: deploy
    plan:
      - get: mediawiki-version
        passed: [update-composer]
      - get: mediawiki-config
        passed: [update-mediawiki-config]
      - put: staging-server
        params:
          interpreter: /bin/bash
          script: |
            export TERM=dumb
            set -e

            echo "((ssh.private_key))" > /tmp/ssh-key
            chmod 600 /tmp/ssh-key
            eval `ssh-agent -s`
            ssh-add /tmp/ssh-key

            cd /data/deployment/deploy/

            ./deploy --updatedb --updatei18n
        ensure:
          put: staging-server
          params:
            interpreter: /bin/bash
            script: |
              export TERM=dumb
              set -e

              rm -rf /tmp/ssh-key
        on_failure:
          put: slack-feed
          params:
            text: ":eyes: Deployment of new mediawiki version failed. :sob:"
        on_success:
          put: slack-feed
          params:
            text: ":tada: Deployment of new mediawiki version finished! :heart_eyes:"
